dist: bionic
language: python
python:
  - "3.7"

install: python3 setup.py install
script: python3 setup.py test
after_success:
  - pip install -r requirements/doc.pip
  - python3 setup.py build_sphinx

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # set in repo settings
    keep-history: true
    local-dir: docs/build/html
    verbose: true
    on:
      branch: master
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    skip_existing: true
    on:
      branch: master
      tags: true
